micronaut:
  application:
   name: micronautGrpc
datasources:
  default:
   url: jdbc:postgresql://localhost:15432/customer-micronaut
   driverClassName: org.postgresql.Driver
   username: postgres
   password: 123456
   sql-dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true