version: "3"

volumes:
  postgres-micronaut:

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: customer-micronaut
      PGDATA: /data/postgresmicronaut
    volumes:
      - postgres-micronaut:/data/postgresmicronaut
    ports:
      - "15432:5432"
